<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BLTPG00TMEG" name="Parameter Test" tests="6" failures="1" timestamp="11 Nov 2017 14:05:35 GMT" time="18.394" errors="0">
  <testcase name="doLogin" time="3.128" classname="javaPackage_InterviewQ.ParameterTest"/>
  <testcase name="doLogin" time="5.747" classname="javaPackage_InterviewQ.ParameterTest"/>
  <testcase name="doLogin" time="0.013" classname="javaPackage_InterviewQ.Assertion_Soft_Assert">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [manoj1] but found [manoj]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [manoj1] but found [manoj]
	at javaPackage_InterviewQ.Assertion_Soft_Assert.doLogin(Assertion_Soft_Assert.java:23)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- doLogin -->
  <testcase name="Logintest1" time="0.002" classname="javaPackage_InterviewQ.TestNG_FirstClass"/>
  <testcase name="Password_Change_test2" time="0.002" classname="javaPackage_InterviewQ.TestNG_FirstClass">
    <skipped/>
  </testcase> <!-- Password_Change_test2 -->
  <testcase name="LogOut_test3" time="0.0" classname="javaPackage_InterviewQ.TestNG_FirstClass">
    <skipped/>
  </testcase> <!-- LogOut_test3 -->
</testsuite> <!-- Parameter Test -->
