<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BLTPG00TMEG" name="TestNG_First" tests="1" failures="1" timestamp="11 Nov 2017 14:04:13 GMT" time="0.056" errors="0">
  <testcase name="doLogin" time="0.032" classname="javaPackage_InterviewQ.Assertion_Soft_Assert">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [manoj1] but found [manoj]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
	expected [manoj1] but found [manoj]
	at javaPackage_InterviewQ.Assertion_Soft_Assert.doLogin(Assertion_Soft_Assert.java:23)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- doLogin -->
</testsuite> <!-- TestNG_First -->
